name: 'Tenderly Virtual TestNet Setup'
description: 'Sets up a Tenderly Virtual TestNet and exposes RPC link as an environment variable'
inputs:
  access_key:
    description: 'Tenderly API Access Key'
    required: true
  project_name:
    description: 'Tenderly Project Name'
    required: true
  account_name:
    description: 'Tenderly Account Name'
    required: true
  testnet_slug:
    description: 'Slug for the Virtual TestNet (must be unique within project)'
    required: true
    default: 'ci_testnet'
  testnet_name:
    description: 'Display name for the Virtual TestNet'
    required: true
    default: 'CI Virtual TestNet'
  network_id:
    description: 'Network ID to fork (e.g., 1 for Ethereum mainnet, 137 for Polygon)'
    required: true
    default: '1'
  chain_id:
    description: 'Chain ID for Virtual TestNet'
    required: false
  block_number:
    description: 'Block number to fork from (in hex or "latest")'
    required: true
    default: 'latest'

runs:
  using: 'node20'
  main: './dist/index.js'
  post: './dist/cleanup.js'
  post-if: always()

branding:
  icon: 'cloud'
  color: 'white'