name: Test Tenderly VNet Action

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Tenderly Virtual TestNet Setup
        uses: Tenderly/vnet-github-action@v1.0.3
        with:
          access_key: ${{ secrets.TENDERLY_ACCESS_KEY }}
          project_name: ${{ vars.TENDERLY_PROJECT_SLUG }}
          account_name: ${{ vars.TENDERLY_ACCOUNT_SLUG }}
          testnet_name: 'Test Network'
          network_id: '1'
          block_number: 'latest'

      - name: Run tests
        env:
          TENDERLY_PROJECT_SLUG: ${{ vars.TENDERLY_PROJECT_SLUG }}
          TENDERLY_ACCOUNT_SLUG: ${{ vars.TENDERLY_ACCOUNT_SLUG }}
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
        run: npm run deploy:vnet